Disable -Wcast-calling-convention for vulkan
The following warning is triggered by the upcoming Clang update to
r271374:

frameworks/native/vulkan/libvulkan/stubhal.cpp:114:12: error: cast
between incompatible calling conventions 'cdecl' and 'aapcs-vfp'; calls
through thispointer may abort at runtime
[-Werror,-Wcast-calling-convention]
    return reinterpret_cast<PFN_vkVoidFunction>(NoOp);

Change-Id: I8de75fd6a3b579a91598aebbdd23bf74b57c3593