Update patch set 2
Patch Set 2:

Please look at this Patch Set. This cause an error while compiling. (sorry my bad english)

frameworks/native/libs/ui/GraphicBufferAllocator.cpp: In member function 'android::status_t android::GraphicBufferAllocator::alloc(uint32_t, uint32_t, android::PixelFormat, int, const native_handle_t**, int32_t*)':
frameworks/native/libs/ui/GraphicBufferAllocator.cpp:134:5: error: no return statement in function returning non-void [-Werror=return-type]
frameworks/native/libs/ui/GraphicBufferAllocator.cpp: At global scope:
frameworks/native/libs/ui/GraphicBufferAllocator.cpp:135:5: error: expected ')' before '(' token
frameworks/native/libs/ui/GraphicBufferAllocator.cpp:135:5: error: expected ')' before '(' token
frameworks/native/libs/ui/GraphicBufferAllocator.cpp:135:5: error: expected ')' before '(' token
frameworks/native/libs/ui/GraphicBufferAllocator.cpp:138:5: error: expected unqualified-id before 'if'
frameworks/native/libs/ui/GraphicBufferAllocator.cpp:178:2: error: expected '}' at end of input
cc1plus: some warnings being treated as errors

make: *** [out/target/product/i9100/obj/SHARED_LIBRARIES/libui_intermediates/GraphicBufferAllocator.o] Error 1

Patch-set: 2