Make bitmap.h C-compatible when __ANDROID_API__ >= 30
C requires a typedef for AHardwareBuffer.

Fixes:
frameworks/native/include/android/bitmap.h:246:9: error: must use 'struct' tag to refer to type 'AHardwareBuffer'

Fixes: 150165785
Test: m checkbuild
Change-Id: I6d475e91317ff7a9264144d4cd6c6c9b46d10196